### ISSUE TITLE
Error popup

### ISSUE THREAD

**Issue by Ghostkiler105** [murrty/YChanEx#13]
Feel free to copy + paste this entire text wall into a new issue on Github

Version: 2.0
Reported Exception: A web exception occured
Message: The remote server returned an error: (404) Not Found.
Stacktrace:    at System.Net.WebClient.DownloadFile(Uri address, String fileName)
   at System.Net.WebClient.DownloadFile(String address, String fileName)
   at Chans.DownloadFile(String FileURL, String Destination, String FileName, Boolean RequireCookie, String RequiredCookie)
Source: System
TargetSite: Void DownloadFile(System.Uri, System.String)
InnerException: 
Response: System.Net.HttpWebResponse
WebAddress: https://8chan.moe/.media/2be087815a048d7347b1b0d91e9da8d1327fd84dc7b1e11c4579733803bb777c.jpg
Full report:
System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.WebClient.DownloadFile(Uri address, String fileName)
   at System.Net.WebClient.DownloadFile(String address, String fileName)
   at Chans.DownloadFile(String FileURL, String Destination, String FileName, Boolean RequireCookie, String RequiredCookie)

**Comment by murrty** [comment]
8chan is fucking weird and it requires "Referer" headers to be set when accessing certain places. I'll have a fix available next release.

**Comment by murrty** [comment]
fixed in 2.1
