### ISSUE TITLE
8chan error

### ISSUE THREAD

**Issue by eymtkzwt** [murrty/YChanEx#16]
I get the following error when attempting to download threads from 8chan. This happens on any thread I tried across multiple boards.

A caught WebException occured.

Message: The remote server returned an error: (888) Unknown HTTP Status.
Stacktrace:    at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at System.Net.WebClient.DownloadString(String address)
   at YChanEx.frmDownloader.GetThreadJSON(String URL, String& JsonString)
   at YChanEx.frmDownloader.<Set8chanThread>b__47_0()
Source: System
Target Site: Byte[] DownloadDataInternal(System.Uri, System.Net.WebRequest ByRef)
Inner Exception: 
Response: System.Net.HttpWebResponse

========== FULL REPORT ==========
System.Net.WebException: The remote server returned an error: (888) Unknown HTTP Status.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at System.Net.WebClient.DownloadString(String address)
   at YChanEx.frmDownloader.GetThreadJSON(String URL, String& JsonString)
   at YChanEx.frmDownloader.<Set8chanThread>b__47_0()
========== END  REPORT ==========

========== OS  INFO ==========
(Please don't omit this info, it may be important)
Current version: 3.0.0
Curernt culture: English (United States)
System Caption: Microsoft Windows 11 Pro
Version: 10.0.22621
Service Pack Major: 0
Service Pack Minor: 0
========== END INFO ==========

**Comment by murrty** [comment]
8chan requires a cookie to be set, and the application does not take into account the cookie. I won't be working on this until my main project focus is wrapped up.

**Comment by LordBarsdale** [comment]
Hopefully, that is soon. Same issue, and other downloaders are also having problems.

**Comment by murrty** [comment]
They seem to change the cookie every now and then, last time I checked it was `disclaimer4`, and now it's `disclaimer5`. If they start a cat and mouse game for this stupid shit, I will drop support.

**Comment by murrty** [comment]
8chan is accessible once again
