### ISSUE TITLE
[Bug] Fool Fuuka threads from desuarchive throw unhandled exception and clos eapplication

### ISSUE THREAD

**Issue by jorganmir** [murrty/YChanEx#21]
Because this happens upon starting the application, it makes it difficult to try and remove the problematic threads as well, causing a loop of crashes

An unrecoverable NullReferenceException occurred and the application will exit.

Message: Object reference not set to an instance of an object.
Type: System.NullReferenceException
Source: System.Windows.Forms
Target Site: System.Object MarshaledInvoke(System.Windows.Forms.Control, System.Delegate, System.Object[], Boolean)
Stacktrace:
   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)

   at YChanEx.frmDownloader.<DownloadFilesAsync>d__58.MoveNext()

--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at YChanEx.frmDownloader.<<RegisterFoolFuukaThread>b__65_0>d.MoveNext()

--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

========== OS  INFO ==========
Current version: 3.0.0-2
Current culture: English (United States)
CLR: .NET Framework 4.8.4644.0 (64-bit)
System caption: Microsoft Windows 10 Home
Version: 10.0.19044
Service Pack major: 0
Service Pack minor: 0
========== END INFO ==========

**Comment by jorganmir** [comment]
An unrecoverable NullReferenceException occurred and the application will exit.

Message: Object reference not set to an instance of an object.
Type: System.NullReferenceException
Source: System.Windows.Forms
Target Site: System.Object MarshaledInvoke(System.Windows.Forms.Control, System.Delegate, System.Object[], Boolean)
Stacktrace:
   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)

   at YChanEx.frmDownloader.<DownloadFilesAsync>d__58.MoveNext()

--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at YChanEx.frmDownloader.<<RegisterFoolFuukaThread>b__65_0>d.MoveNext()

--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

========== OS  INFO ==========
Current version: 3.0.0-2
Current culture: English (United States)
CLR: .NET Framework 4.8.4644.0 (64-bit)
System caption: Microsoft Windows 10 Home
Version: 10.0.19044
Service Pack major: 0
Service Pack minor: 0
========== END INFO ==========
